[package]
name = "core-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen-guest-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", version = "0.3.0" }
wee_alloc={ version = "0.4.5", optional = true }

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 'z'
wasm-opt = true
lto = true

[features]
default = ["wee_alloc"]
