/**
 * This file was automatically generated by generate-json-schema-to-ts.js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source file JSON file: typescript-checker-options.json,
 * and run 'npm run generate' from monorepo base directory.
 */
export interface TypescriptCheckerPluginOptions {
    typescriptChecker: TypescriptCheckerOptions;
}
/**
 * Configuration for @stryker-mutator/typescript-checker
 */
export interface TypescriptCheckerOptions {
    /**
     * Configures the performance of the TypescriptChecker. Setting this to false results in a slower, but more accurate result.
     */
    prioritizePerformanceOverAccuracy: boolean;
}
//# sourceMappingURL=typescript-checker-options.d.ts.map