/**
 * This file was automatically generated by generate-json-schema-to-ts.js.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source file JSON file: typescript-checker-options.json,
 * and run 'npm run generate' from monorepo base directory.
 */
export {};
//# sourceMappingURL=typescript-checker-options.js.map